### ISSUE TITLE
LibWeb: CSS variables don't support CSS-wide keywords correctly

### ISSUE THREAD

**Issue by aplefull** [LadybirdBrowser/ladybird#1157]
Currently css variables don't support second argument. An optional second argument to the function should work as a fallback value.

Example:   

```CSS
<style>
    :root {
        --a: initial;
    }

    body {
        background: var(--a, crimson);
    }
</style>
```
<table>
<tr>
<th>Chrome</th>
<th>Ladybird </th>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/bc40ca07-4489-4481-941b-d2a7550b30f4)

</td>
<td>

![image](https://github.com/user-attachments/assets/83bdf045-4bee-44c7-8bb2-bb356698f988)

</td>
</tr>
</table>
