### ISSUE TITLE
LibWeb: CSS `translate()` doesn't take border into account

### ISSUE THREAD

**Issue by aplefull** [LadybirdBrowser/ladybird#1269]
I'm using a div with 0px height so that difference is more visible. Same happens when element has a height.

Example:
```CSS
<style>
    div {
        border: 20px solid crimson;
        transform: translateY(100%);
    }
</style>
<div></div>
```   

<table>
<tr>
<th>Chrome</th>
<th>Ladybird </th>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/7cecef87-352f-4362-9f74-612ad184cee0)

</td>
<td>

![image](https://github.com/user-attachments/assets/3e74855d-59b2-47e3-961d-0f9242cf4243)

</td>
</tr>
</table>
