### ISSUE TITLE
LibWeb: Styles inside `@media` are ignored if there is no query

### ISSUE THREAD

**Issue by aplefull** [LadybirdBrowser/ladybird#1551]
I'm not sure if `@media` without actual query is valid but Chrome and Firefox seem to apply styles anyway. This reduction also comes from a real website iirc, so things like that exist in the wild. 

Example:

```CSS
<style>
    @media {
        body {
            background-color: crimson;
        }
    }
</style>
```

<table>
<tr>
<th>Chrome/Firefox</th>
<th>Ladybird </th>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/b0bec4bc-f72b-49d5-8d6f-2fc33ed452f3)

</td>
<td>

![image](https://github.com/user-attachments/assets/9528dd49-e07c-45d3-81b5-4909af93853c)

</td>
</tr>
</table>
