### ISSUE TITLE
LibWeb: Children don't inherit parent's opacity in a grid layout

### ISSUE THREAD

**Issue by aplefull** [LadybirdBrowser/ladybird#1552]
Example:

```CSS
<style>
    body {
        display: grid;
    }

    .a {
        opacity: 0;
    }

    .b {
        background-color: crimson;
        width: 40px;
        height: 40px;
    }
</style>

<div class="a">
    <div class="b"></div>
</div>

```

<table>
<tr>
<th>Chrome</th>
<th>Ladybird </th>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/520d7186-e3cd-464d-9de4-1222e25e8c2d)

</td>
<td>

![image](https://github.com/user-attachments/assets/fafb4c4d-3e77-4f63-8f9a-ced1928942d6)

</td>
</tr>
</table>
