### ISSUE TITLE
backdrop-filter with calc() fails to render

### ISSUE THREAD

**Issue by rubenwardy** [LadybirdBrowser/ladybird#18]
The backdrop-filter on an element fails to render if it contains a `calc()`. It works if you replace the calc with `70%`

```css
body {
    background: blue url("cat.jpg");
}

.panel {
    display: inline-block;
    background: magenta;
    border-radius: 2rem;
    padding: 0.6rem 1.2rem;
    margin: calc(50% / 2);
    color: white;
}

@supports (backdrop-filter: brightness(70%) contrast(110%) saturate(140%) blur(12px)) {
    .panel {
        background: none;
        backdrop-filter: brightness(calc(100% - 50% / 1.666666667)) contrast(110%) saturate(140%) blur(12px);
    }
}
```

[ladybird_backdrop_filter.zip](https://github.com/user-attachments/files/15535678/ladybird_backdrop_filter.zip)

Expected

![image](https://github.com/LadybirdWebBrowser/ladybird/assets/2122943/0e814f06-7a59-47bd-845e-e9b9b91c5d9f)

Actual

![image](https://github.com/LadybirdWebBrowser/ladybird/assets/2122943/e52431ee-1d9d-4a1d-94e4-d5c67746ecbe)
