### ISSUE TITLE
Computed font-size crashes at as_length()

### ISSUE THREAD

**Issue by shlyakpavel** [LadybirdBrowser/ladybird#2098]
I came around
https://wpt.fyi/results/svg/styling/use-element-animations.html
The test includes the following code
```css
  @keyframes font-anim {
    0% { /* starts from computed font-size */ }
    100% { font-size: 80px; }
  }
```
That crashes Ladybird.
As a workaround, I patched it with https://gist.github.com/shlyakpavel/8c5709b92de5569fd328691b8a66f0e1
Any idea how to implement/fix that correctly? I'd be willing to leave a PR as soon as there's an idea how to handle that correctly
