### ISSUE TITLE
Flashbang (white background) effect before page loads: sweclockers.com

### ISSUE THREAD

**Issue by ExileFox** [LadybirdBrowser/ladybird#695]
Just tested this browser and this is something that doesn't happen with firefox/chromium and it's forks.

I don't know the cause of this issue, but I'm running Linux and I suspect more sites might have similar issues.

**Comment by AtkinsSJ** [comment]
Looking at the site, the relevant CSS is this:

```css
body {
	background: var(--background-main, #edeceb);
}

@media (prefers-color-scheme: dark) {
    :root.os-default {
        --background-main: #101010;
    }
}
```
On load, the `<html>` element doesn't have a class set, so the background colour is the fallback near-white `#edeceb`. Then at some point JS adds the `os-default` class, and so the `--background-main` value exists and is used.

I'm not 100% sure here because `#edeceb` looks so much like white, so it might be something else. But it's definitely suspicious. Maybe we're either taking longer to run JS than other browsers, or we're not waiting as long before first paint.
