### ISSUE TITLE
document.write does not write the text from the DevTools

### ISSUE THREAD

**Issue by matan-h** [LadybirdBrowser/ladybird#970]
On a new tab, I opened the `Inspector` [f12] console, and write `document.write("text")`. The color change, but the text is not written.
Note that I can see the text after I run `document.write("<p> new text </p>")` but then I don't see the `new text`, just `text` (its also doesnt work with empty `p` tag nor with other plain text)

about:
```yml
Version: 1.0
Arch:  x86_64
Operating System:  Linux <Fedora KDE 40>
Git hash <git rev-parse HEAD>: 41cf9f6fe3f6a36094a8db3ace0733e1e3666092
````
