### ISSUE TITLE
F12 shortcut to close the Inspector don't work.

### ISSUE THREAD

**Issue by matan-h** [LadybirdBrowser/ladybird#972]
On a new tab, I opened the `Inspector` using f12, and naturally tried to close it using f12 again (when it is in focus). This is not what happened: instead, the DOM Tree just move one element up.

EDIT: I found the cause of the element up: the `inspector.js` uses the deprecated `event.keyCode` instead of `event.key`, and `F12` and up arrow have the same `keycode` (only in ladybird, doesn't do the same in other browsers, `F12` supposed to be `123`).

About:
```yml
Version: 1.0
Arch:  x86_64
Operating System:  Linux <Fedora KDE 40> [Wayland]
Git hash <git rev-parse HEAD>: 41cf9f6fe3f6a36094a8db3ace0733e1e3666092
````
