### ISSUE TITLE
`event.keycode` is incorrect on function keys

### ISSUE THREAD

**Issue by matan-h** [LadybirdBrowser/ladybird#974]
This is discovered through the #972 issue. 
On a website like this:
```html
<script>
    document.addEventListener("keydown", event =>console.log(event.key,event.keyCode))
</script>
```

when the user presses the function keys, the `event.key` is the correct name, but `event.keyCode` equal `<the correct value>-85` (e.g. `F12` is supposed to be `123` is `38`.) 
other function key get other margins:

key    | Correct keyCode | ladybird keyCode
|--------|--------|--------|
| F1 | 122 | 27 |
| NumLock | 144 | 25 |
| ScrollLock | 145 | 26 | 
| Delete | 46 | 6 |
| Insert | 45 | 5 |

My intuitive thought was to implement the function keys in [`KeyboardEvent.cpp`](https://github.com/LadybirdBrowser/ladybird/blob/1e7b17f15024d0618f1a1e17e3e927856febde28/Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp#L54) because capsLock seems to be implemented there, but I don't understand c++ that much.

<details>
<summary>Version</summary>

```yml
Version: 1.0
Arch:  x86_64
Operating System:  Linux <Fedora KDE 40> [Wayland]
Git hash <git rev-parse HEAD>: 1e7b17f15024d0618f1a1e17e3e927856febde28
```
</details>
