### ISSUE TITLE
JavaScript event report Unidentified when pressing keys with Ctrl.

### ISSUE THREAD

**Issue by matan-h** [LadybirdBrowser/ladybird#984]
This is somewhat similar to #974, just when `ctrl` is pressed, and the JavaScript act even weirder.
 On a website like this:
```html
<script>
    document.addEventListener("keydown", event =>console.log(event.key,event.keyCode))
</script>
```
When the user presses the Ctrl+<x>, the `event.key` AND the `event.keyCode` both incorrect. (e.g. `ctrl+x` ⇒ "Unidentified" 95)
It looks like it's an issue with the Qt interface, since Qt itself change the code_point for keys pressed with control to be alphabetically coded (e.g. a=1,b=2). I've [tried](https://github.com/LadybirdBrowser/ladybird/compare/master...matan-h:ladybird:control-shortcuts1) to make it work by adding `0x60` and convert from Unicode (so 1 convert to `a`, etc.).

I notice that when using this solution out of the a-z letters, it correctly solves the keys after the `0x60` Unicode like `ctrl+}` but for some reason, it also makes the shortcuts `ctrl+5` equal `ctrl+}` output the same `event.key` (`}`), despite having two different keycodes: `60` and `221`. I have no idea why.

<details>
<summary>Version</summary>

```yml
Version: 1.0
Arch:  x86_64
Operating System:  Linux <Fedora KDE 40> [Wayland]
Git hash <git rev-parse HEAD>: 41949f2ed1b8f62d0530ee9a1478f1b53a6263aa
```
</details>
